### ISSUE TITLE
Unit test failures on Windows?

### ISSUE THREAD

**Issue by wolfv** [conda-forge/libignition-rendering4-feedstock#1]
For some reason half the tests currently fail on Windows (all tests that start with `check_...` while the corresponding tests without `check_` seem to be fine. (https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=268364&view=logs&jobId=a70f640f-cc53-5cd3-6cdc-236a1aa90802&j=a70f640f-cc53-5cd3-6cdc-236a1aa90802&t=f5d15007-a01c-5ad8-c9ce-4d519d3b275f)

Any ideas @JShep1 ?

I am unsure what's different here vs. staged recipes. We need to solve this issue to get a successful upload of the win-64 package (osx and linux are available now: https://anaconda.org/conda-forge/libignition-rendering4)

**Comment by traversaro** [comment]
The `check_` tests are just a Python-based check that the regular tests produced the expected XML result files. Probably we just need to add Python to the build dependencies, let me check.

**Comment by traversaro** [comment]
See https://github.com/ignitionrobotics/ign-cmake/blob/bed3f7b2b2d0210b35808b2cfa17026169f7c4b4/cmake/IgnUtils.cmake#L1715 and https://github.com/ignitionrobotics/ign-rendering/blob/ign-rendering4/tools/check_test_ran.py .

**Comment by wolfv** [comment]
great! fixed
